steps:

  - commands: 
    - bundle install
    - RACK_ENV=test bundle exec rake db:drop
    - RACK_ENV=test bundle exec rake db:create
    - RACK_ENV=test bundle exec rake db:migrate
    - bundle exec rspec
    label: ":rspec:"
    artifact_paths:
      - coverage/*
  
  - wait

  - commands: 
    - "yarn install"
    - "tsc -p client --declaration false"
    label: ":typescript:"

  - wait
  
  - commands: 
    - "yarn install"
    - "yarn lint"
    label: ":eslint:"

  - wait
  
  - commands: 
    - "yarn install"
    - "yarn test --collectCoverage"
    label: ":jest:"
    artifact_paths:
      - coverage/*

  - wait

  - name: ":codeclimate:"
    commands:
      - '.buildkite/report-coverage.sh'

  - wait 

  - commands:
      - "yarn install"
      - "yarn build"
      - "yarn cypress:ci"
    label: ":parcel: :cypress:"
    artifact_paths:
      - cypress/videos/*
      - .parcel-bundle-reports/*